config/routes.rb
Rails.application.routes.draw do
  resources :hotels

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:edit, :update, :destroy]
  before_action :config_expedia, only: [:index, :show]

  # GET /hotels
  # GET /hotels.json
  def index

    response = @api.get_list({:destinationString => 'Media', :stateProvinceCode => 'PA'})
    @hotels = response.body['HotelListResponse']['HotelList']['HotelSummary']

  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    response = @api.get_list({:hotelId => @hotel_id, :destinationString => 'Media'})
    @hotel = response.body['HotelListResponse']['HotelList']['HotelSummary'][0]
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel_id = params[:id]
    end

    def config_expedia

      Expedia.cid = 55505
      Expedia.api_key = 'yt2mfcm9eua5dydntsd477qs'
      Expedia.shared_secret = 'Z7ctwvaN'
      Expedia.locale = 'en_US'
      Expedia.currency_code = 'USD'
      Expedia.minor_rev = 13
      @api = Expedia::Api.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params[:hotel]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.haml
= form_for @hotel do |f|
  - if @hotel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hotel.errors.count, "error")} prohibited this hotel from being saved:"
      %ul
        - @hotel.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/hotels/edit.html.haml
%h1 Editing hotel

= render 'form'

= link_to 'Show', @hotel
\|
= link_to 'Back', hotels_path

app/views/hotels/index.html.haml
%h1 Listing hotels

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th Hotel
      %th City
      %th
  %tbody
    - @hotels.each do |hotel|
      %tr
        %td= hotel['name']
        %td= hotel['city']
        %td= link_to 'Details', hotel_path(hotel['hotelId'])
%br

app/views/hotels/new.html.haml
%h1 New hotel

= render 'form'

= link_to 'Back', hotels_path

app/views/hotels/show.html.haml
%p#notice= notice

%div.row
  %div.col-sm-8
    %div.row
      %div.col-sm-8
        %h1= @hotel['name']
      %div.col-sm-4.hotel-star
        %small Rating
        %br
        - @hotel['hotelRating'].times do
          %span.glyphicon.glyphicon-star

%div.row
  %div.col-sm-8
    %h2= @hotel['city']
    %p= @hotel['shortDescription']

= link_to 'Edit', edit_hotel_path(@hotel)
\|
= link_to 'Back', hotels_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#trip-header">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="#">Trip</a>
    </div>

    <div class="collapse navbar-collapse" id="trip-header">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= hotels_path %>">Hotels</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
      </ul>
    </div>

  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>